Implicit Monads
melt-umn/silver pull request #384
Opened 2020-11-05 16:53 UTC by RandomActsOfGrammar

This allows monads to be used implicitly in equations.

It also adds an example of the simply-typed lambda calculus to the tutorials which makes use of implicit monads.

2020-11-05 17:56 UTC, krame505 requested changes
Wow, there's a lot more here that I thought!  (Having not really looked at what you were working on in this branch too closely.)

Just a (relatively) few things to fix/discuss.

2020-11-05 17:56 UTC, krame505 commented on grammars/core/monad/Either.sv
> +
These type-specific functions will probably all go away once we have type classes.  But probably ok to add them for now.

2020-11-05 17:56 UTC, krame505 commented on grammars/core/monad/State.sv
> +abstract production modifyState
Could forward to `bindState(getState(), \ x::s -> setState(fun(x)))`, I suppose.  But as-is is probably a little more efficient, IDK.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/composed/Default/Main.sv
> +
Why are you explicitly re-including these?  All of them should be exported by `silver:host` (`silver:host:core` is just the core language without any extensions or modifications enabled.)  The point is that we don't want to keep this list in more than one place.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/definition/core/GlobalDcl.sv
> +  top.errors := t.errors ++ e.errors;
Why the explicit equation for `errors` here?  This is auto-computed as a monoid attribute.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/definition/flow/env/ProductionDcl.sv
> +{-
Delete?  We generally don't want to keep commented out chunks of obsolete code sitting around.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/BuiltInFunctions.sv
> +  top.monadRewritten = if !isList && isMonad(e.mtyperep)
A bit of a nit-pick, but stylistically we generally always line break and indent after `=` when there are long equations, rather than aligning the whole body after the `=`.  Don't feel obligated to change it though.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/BuiltInFunctions.sv
> +  TODO I don't know what these are supposed to be, really, but I suppose they should be bound in if they're monads?
This is the explicit terminal value constructor (e.g. `terminal(Identifier_t, "foo", bogusLoc)`) - this should be handled just like any other operator or literal, I suppose.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/BuiltInFunctions.sv
> +
No need to include aspect equations for forwarding productions?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Case.sv
> +            let ty::Type = decorate a with {env=top.env; mDownSubst=ml.mUpSubst; frame=top.frame;
Why not just extract the match rule expression here and decorate that instead of decorating the entire match rule?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Case.sv
> +            let ty::Type = decorate a with {env=top.env; mDownSubst=ml.mUpSubst; frame=top.frame;
Ditto.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Case.sv
> +attribute env, mDownSubst, merrors, mtyperep, frame, grammarName, compiledGrammars,
These would all cause orphaned-occurs flow error - technically I think you should define all new attributes with the same types and use them here.  But as mentioned above, I think you can just add an attribute to extract the match rule expression and decorate that instead, since these are all just copied down anyway?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Case.sv
> +--  top.errors := p.errors;
Generally we would like to avoid leaving lots of commented out equations, unless there is a reason we would like to include them but can't, in which case there should be a justifying comment.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/CopperExpr.sv
> +  I honestly have no idea if these can occur in a production.  I kind of doubt
These can only occur in copper action blocks, which reuse the same syntax as production bodies and expressions.  I don't think you would be applying any rewriting inside action blocks, but I guess it's still good to include these for completeness.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/DclInfo.sv
> +abstract production restrictedSynDcl
Technically these should all be non-forwarding since `DclInfo` is a closed nonterminal - doing so avoids interfering equations, too.  See https://github.com/melt-umn/silver/blob/develop/grammars/silver/extension/autoattr/DclInfo.sv for example.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Expr.sv
> +  --need to check it is compatible with the function return type
Commented out code - is this important?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Expr.sv
> +top::Expr ::= 'if' e1::Expr 'then' e2::Expr 'end' --this is easier than anything else to do
Seems like a reasonable syntactic decision.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Lambda.sv
> +--- Concrete Syntax for lambdas
Uhh abstract syntax for lambdas?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Let.sv
> +--- Concrete Syntax for lets
Ditto

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/PrimitiveMatch.sv
> +aspect production matchPrimitiveConcrete
Remove empty aspects?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/ProductionBody.sv
> +  return case l of
Could just be a `map`, I think?  Took me a second wondering why this was recursive.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/ProductionDcl.sv
> +grammar silver:extension:implicit_monads;
Delete?

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/ProductionBody.sv
> +terminal Implicit_kwd    'implicit'     lexer classes {KEYWORD,RESERVED};
Nit: this terminal declaration should go before `emptyAttributeDef`.  

Also have you checked that these actually need to be reserved?  Generally we want to avoid introducing new reserved keywords and lean on context-aware scanning whenever possible.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Types.sv
> +
Hmm, I thought we decided to go with lower case for these?  Upper case is inconsistent with ...every other declaration keyword in Silver.  I realize that these are kind of like types, but these aren't actually type expressions so having them upper case would be confusing.  The convention we have adopted for `functor`, `monoid`, etc. is lower case too, despite these being "sort of" types.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Types.sv
> +abstract production explicitType
Is the purpose of these types just to give nicer error messages?  Neat idea.  I would maybe just change the pp to `"restricted " ++ t.typepp` or `"implicit " ++ t.typepp` though, having comment symbols show up in error messages seems potentially confusing (and not especially helpful.)

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Types.sv
> +
These productions don't actually need to have interfering equations for `defs`, you can just forward to `defsAGDcl` - see https://github.com/melt-umn/silver/blob/develop/grammars/silver/extension/autoattr/Functor.sv#L3 for example.

2020-11-05 17:56 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Util.sv
> +function monadPlus
Shouldn't these functions be *monoid* plus and zero?  These operations aren't really connected directly to monads AFAIK, they just are available for monads that also happen to be monoids.

2020-11-05 18:48 UTC, RandomActsOfGrammar commented on grammars/silver/composed/Default/Main.sv
> +
This is probably from when I started last year and didn't understand as much about how it worked.  I'll change this file to the `develop` version.

2020-11-05 18:50 UTC, RandomActsOfGrammar commented on grammars/silver/definition/core/GlobalDcl.sv
> +  top.errors := t.errors ++ e.errors;
I'll get rid of it.  This is leftover from my original attempt.

2020-11-05 18:50 UTC, RandomActsOfGrammar commented on grammars/silver/definition/flow/env/ProductionDcl.sv
> +{-
Agreed.

2020-11-05 18:51 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/BuiltInFunctions.sv
> +  top.monadRewritten = if !isList && isMonad(e.mtyperep)
I have those all over the place, so I won't change it.  I will try to keep it in mind for the future.

2020-11-05 18:55 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/BuiltInFunctions.sv
> +
I'll remove them.

2020-11-05 22:18 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/BuiltInFunctions.sv
> +  TODO I don't know what these are supposed to be, really, but I suppose they should be bound in if they're monads?
I added actual rewriting for it.

2020-11-05 22:33 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/DclInfo.sv
> +abstract production restrictedSynDcl
I changed them to be non-forwarding and copied the equations for the other attributes from the existing `DclInfo` productions.

2020-11-05 22:35 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/Lambda.sv
> +--- Concrete Syntax for lambdas
Removed---I'm guessing it came from copying the original file.

2020-11-05 22:35 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/Let.sv
> +--- Concrete Syntax for lets
Ditto.

2020-11-05 22:42 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/ProductionBody.sv
> +  return case l of
It could be a `map`.

2020-11-05 22:43 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/ProductionDcl.sv
> +grammar silver:extension:implicit_monads;
Yes.  This is from my initial attempt, which rewrote in monadic productions, rather than particular equations.

2020-11-06 03:29 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/Util.sv
> +function monadPlus
We could change them to that.  I don't see any point to changing them; we shouldn't need them once we have type classes, and they are for monadification right now.

2020-11-06 03:30 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/Types.sv
> +abstract production explicitType
These types are how implicit and restricted attributes are actually tracked to ensure attribute access restrictions are followed.  For example, implicit equations check that any attributes accessed inside them have an `implicit` type or a `restricted` type.

The comment in the `typepp` was for debugging purposes when I couldn't figure out why it was doing what it was doing.  I'll remove it.

2020-11-06 03:43 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/Types.sv
> +
I removed the equations for `defs`.

2020-11-06 05:07 UTC, krame505 commented on grammars/silver/extension/implicit_monads/Types.sv
> +abstract production explicitType
Hmm, that is potentially brittle- generally pattern matching on a forwarding production is the same as writing an interfering equation. 
For attribute accesses, couldn't you just check the `DclInfo` that you get from looking up the attribute to see if it is restricted or implicit? You can define new attributes/match on your new non-forwarding `DclInfo` productions without issue since that nonterminal is closed and you have a default (i.e. unrestricted.)

2020-11-06 15:19 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/ProductionBody.sv
> +terminal Implicit_kwd    'implicit'     lexer classes {KEYWORD,RESERVED};
If I remove `Reserved`, I get the following Copper error for all three:
```
Unresolvable lexical ambiguity at parser states   [191,639,769,906,1091,1461] between terminals: 
       [silver:definition:core:IdLower_t,'implicit']
```

2020-11-06 15:24 UTC, RandomActsOfGrammar commented on grammars/silver/extension/implicit_monads/Types.sv
> +
I'm changing it to use the lowercase terminals.

2020-11-06 22:28 UTC, krame505 commented on grammars/silver/extension/implicit_monads/ProductionBody.sv
> +terminal Implicit_kwd    'implicit'     lexer classes {KEYWORD,RESERVED};
Hmm, nevermind - I forgot that these are used inside production bodies (where there would be an ambiguity with equation LHS names.)

2020-11-07 16:20 UTC, RandomActsOfGrammar commented
I think I addressed all your comments, Lucas.  However, I'm having a problem with marked equations, so this shouldn't be merged.

When I try to write marked equations for `restricted` or `implicit` attributes, I end up with an infinite computation.  For example, the following grammar does not work:
```
imports core:monad;

restricted synthesized attribute res1::Integer;

nonterminal Nt1 with res1;

abstract production p
top::Nt1 ::=
{
  restricted top.res1 = 5;
}
```
There isn't any reason I can see why this shouldn't work.  The affected productions are `implicitAttributeDef` and `restrictedAttributeDef` in `ProductionBody.sv`.  I thought the problem was with accessing `attr.attrDcl`, but empty equations (`implicit t.a = ;` from production `emptyAttributeDef`) work just fine, and they are essentially the same as other implicit equations.

I have no idea what else to look at to figure out what the problem is.  Lucas, do you have any ideas?

2020-11-08 00:00 UTC, krame505 commented
Wait, I thought you were getting rid of the various explicitly-marked concrete equation productions, now that equations are overloaded?  Keeping them seems overly complicated, since one would presumably never e.g. have an `implicit` equation for an attribute declared as `restricted`.  Removing these could also allow for the `restricted` and `unrestricted` terminals to not be reserved.  

Also it seems you are doing error checking on the concrete productions - what is the reason for this?  I would think that you would want to perform these checks on the abstract productions to which the overloaded equations would dispatch.  I haven't looked too closely, but this may fix the infinite recursion issues you are seeing.

2020-11-08 00:13 UTC, RandomActsOfGrammar commented
By keeping the markers in addition to overloading equations, we can maintain consistency with the paper.

The only error checking I'm doing on the concrete productions is that they're being used for the correct mode of attribute, such as checking that an implicit equation is defining an implicit attribute.  The rest of the checking is being done on the abstract productions.

2020-11-08 03:31 UTC, krame505 commented
Ah, that seems reasonable.  

The problem seems to be that you are forwarding based on the result of looking up the attribute in the environment, which eventually depends on `defs` for all `ProductionStmt`s in the production body (due to the mutually recursive nature of production bodies.)  This introduces a circularity since the `defs` are attempted to be computed via forwarding in `implicitAttributeDef`, etc.  See the comment on `attributeDef` in `silver:definition:core:ProductionBody.sv`.  You should be able to fix this by providing explicit empty equations for `defs` (and also `productionAttributes`, for similar reasons) as on `attributeDef`.  This isn't interfering, since these attributes should always be empty anyway based on what is forwarded to.

2020-11-08 04:44 UTC, RandomActsOfGrammar commented
Thank you.  Yes, that fixed it.  If you want to take another look, I think it should meet with your approval.

2020-11-08 22:48 UTC, RandomActsOfGrammar commented
It occurred to me that the mode types were no longer necessary.  I removed them and added a missing check for not redefining attribute names, with other error checking I found on the normal attribute-defining productions.

2020-11-08 23:25 UTC, krame505 approved these changes

2020-11-08 23:28 UTC, merged