Feature/better aspect syntax
melt-umn/silver pull request #435
Opened 2021-01-13 17:32 UTC by hypnoticOxbow

Improves Aspect syntax such that it supports the following convenience syntax.
```
aspect isLValue on Expr of
| declRefExpr(_) -> true
| arraySubscriptExpr(lhs, _) -> lhs.isLValue
| memberExpr(lhs, _, _) -> lhs.isLValue
| _ -> false
end;
```
which would forward to
```
aspect production declRefExpr
top::Expr ::= _
{ top.isLValue = true; }

aspect production arraySubscriptExpr
top::Expr ::= lhs::Expr _
{ top.isLValue = lhs.isLValue; }

aspect production memberExpr
top::Expr ::= lhs::Expr _ _
{ top.isLValue = lhs.isLValue; }

aspect default production
top::Expr ::=
{ top.isLValue = false; }
```
When Clauses and multiple patterns with the same production are not supported. When clauses are an odd fit here, and the structure of the example seems to suggest that each production pattern produces one aspect production, and multiple patterns would cause issues with multiple aspect productions that change the same attribute (This behavior produces a warning in silver). When clauses require multiple patterns with the same production afaict, and I'm not certain how the semantics would work in the generated aspect production (what happens if the when clause is false?). If people have different ideas on those aspects please let me know.

2021-01-13 17:48 UTC, krame505 commented
If there are multiple clauses with the same production, then this should generate a single aspect production containing a pattern match:
```
synthesized attribute simplify::Expr;
aspect value on Expr of
| addExpr(a, 0) -> a.simplify
| addExpr(a, b) -> addExpr(a.simplify, b.simplify)
| e -> e
```
should become
```
aspect production addExpr
top::Expr ::= a::Expr _e2::Expr
{
  top.simplify =
    case _e2 of
    | 0 -> a.simplify
    | b -> addExpr(a.simplify, b.simplify)
   end;
}
aspect default production
top::Expr ::= 
{ top.simplify = top; }
```
You might find it easiest when there are multiple patterns to just use generated names for all of the children in the production signature and matching on all of them in the production's case expression.  When-clauses can be handled similarly by including a case expression in the translation.  

If the patterns turn out to be overlapping or incomplete, then the appropriate warnings/errors should show up in the generated translation.

2021-01-13 19:00 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +    | _ -> error("invalid production type")
this also fails on when the user uses a not-imported type, so definitely needs some "proper" error reporting

2021-01-13 19:01 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +    map((\asp::AspectRHSElem -> case asp of
generate the names as a list as a separate attr, and have `prodParamsList` and `prodParamNames` as `zip()`s of it? might be more readable /shrug

2021-01-13 19:02 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +        { top.$QName{top.aspectAttr} = $Expr{caseExpr_c('case',
consider factoring the `caseExpr_c` out to a local, again for readability

2021-01-13 19:05 UTC, krame505 commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +        { top.$QName{top.aspectAttr} = $Expr{caseExpr_c('case',
And consider just using the abstract `caseExpr` production here instead of `caseExpr_c`.

2021-01-13 19:23 UTC, remexre commented
"stretch goal," but it'd be nice if this worked on collection attributes too. I suppose it'd have to specify `:=` vs `<-` if so

2021-01-14 00:46 UTC, krame505 commented
After thinking this over a bit more, I guess I agree that it makes sense to always specify `:=` vs `<-` - this is at least consistent as both collection operators are distinct from the `=` used for regular attributes, so it makes sense that the aspect equation syntax should be different for all three as well.  

I'm not super happy about the `with :=`/`with <-` syntax though - this feels to me too much like the `with <op>` used in declaring collections (although I can live with this syntax if that's what we pick.)  What do people think about
```
aspect base errors on Expr of ... end
```
and
```
aspect contrib errors on Expr of ... end
```
?

2021-01-14 14:59 UTC, ericvanwyk commented
I would prefer `using :=` and `using <-` or something besides `with` since it is overloaded.  `aspect contrib` doesn't reall speak to me however.

It does seem odd that we write `aspect production` but here only `aspect` - instead of `aspect attribute` or something.  But it might be that `aspect production` is the thing that is a bit verbose...

2021-01-14 17:49 UTC, krame505 commented
I agree `using` is probably better than `with`.  

I had the same thought about `aspect attribute`, but I do think that it is clear enough from the `<name> on <NT>` bit that `<name>` is an attribute.  Our syntax for flow specifications is `flowtype errors {env} on Expr;` which is quite similar.

2021-01-14 22:05 UTC, ericvanwyk commented
Good point on the `flowtype` stuff - `aspect <attr> on <NT> using := ...` sounds good to me.

2021-01-16 19:44 UTC, hypnoticOxbow commented
Am I still throwing a warning on '<-' or is there sufficient consensus here that this syntax won't be changed?

2021-01-16 19:46 UTC, krame505 commented
I think the syntax we've settled on is good, it's not ambiguous if we always require `:=` or `<-` to specified with collections.

2021-01-17 22:12 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +    map((\asp::AspectRHSElem -> case asp of
Done.

2021-01-17 22:29 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +        { top.$QName{top.aspectAttr} = $Expr{caseExpr_c('case',
This has been done.

2021-01-17 23:22 UTC, remexre requested changes

2021-01-17 23:22 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        top::$TypeExpr{aspectTy} ::= $AspectRHS{prodParams}
were you going to gensym top? actually, would like others' opinions on this: should `top` be in scope for body exprs? imo `top` should be a keyword at this point... (will argue this whenever we redo syntax...)

for consistency could be like

```
aspect foo on top::Bar of
...
end
```

but that's another syntax change :P

(though, that might just be changing the type to an AspectProductionLHS or w/e?)

2021-01-17 23:22 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +  local defTop::DefLHS = concreteDefLHS(qNameId(name("top",location), location=location), location=location);
see prev comment

2021-01-17 23:22 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        [wrn(location, "wildcard patterns after this one are dead code.")])
uh wait what are the match semantics?

```
aspect unparse on stlc:Type of
| _ -> "unknown"
| arr(t1, t2) -> t1.unparse ++ " -> " ++ t2.unparse
end
```

what's `arr(bool(), bool()).unparse()`? `unknown` or `unknown -> unknown`

2021-01-17 23:22 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        name("__generated_" ++ toString(genIntReally(pat)), top.location),
I think `genIntReally` is unnecessary when partial function application isn't being used

2021-01-17 23:22 UTC, remexre commented on self-compile
> +SVJVM_FLAGS=${SVJVM_FLAGS:-"-Xmx3G -Xss64M"}
note for other reviewers: this was needed for mwda to work on silver...

2021-01-17 23:22 UTC, remexre commented on grammars/silver/compiler/modification/copper/ParserDcl.sv
> +terminal Parser_kwd 'parser' lexer classes {RESERVED};
should this be `KEYWORD,RESERVED`?

2021-01-17 23:22 UTC, remexre commented on grammars/silver/compiler/extension/convenienceaspects/Project.sv
> +imports silver:compiler:analysis:typechecking:core;
are all of these necessary?

2021-01-17 23:24 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +         | _ -> error("This error indicates possible productions for AbstractMatchRule have expanded.")
hmm, maybe I'll remove it actually, as I haven't found any other productions for matchRule, so this match is actually complete.

2021-01-17 23:25 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        top::$TypeExpr{aspectTy} ::= $AspectRHS{prodParams}
I wasn't going to, but I could also do it too. I don't have strong opinions on usage of top in your aspect production.

2021-01-17 23:27 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        [wrn(location, "wildcard patterns after this one are dead code.")])
you get one default aspect production for unknown, one for the arr production
Note that these productions are grouped, so if you have a wildcard production match like this, that means there are more than one match with just wildcard

2021-01-17 23:28 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        name("__generated_" ++ toString(genIntReally(pat)), top.location),
his change has been made.

2021-01-17 23:28 UTC, hypnoticOxbow commented on grammars/silver/compiler/modification/copper/ParserDcl.sv
> +terminal Parser_kwd 'parser' lexer classes {RESERVED};
maybe. All I know is I asked "should I change this to reserved" in the meeting and got an answer of yes.

2021-01-17 23:30 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/Project.sv
> +imports silver:compiler:analysis:typechecking:core;
no, but I haven't yet gotten around to checking every one cause its like tedious. I'll fix this in a bit

2021-01-17 23:31 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        [wrn(location, "wildcard patterns after this one are dead code.")])
ok I'm more confused by your example too. Its `unknown -> unknown` because thats what you've provided here.

2021-01-17 23:35 UTC, krame505 commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        top::$TypeExpr{aspectTy} ::= $AspectRHS{prodParams}
You should definitely have some way reference `top` in easy-aspect productions.  To be consistent with strategy attributes/rewriting, maybe consider syntax such as
```
aspect foo on top::Expr of
| prod(x) -> top.bar
end;
```
and use the specified name as the LHS, if provided, or otherwise gensym it?

2021-01-17 23:40 UTC, krame505 commented on grammars/silver/compiler/extension/patternmatching/Case.sv
> +nonterminal AbstractMatchRule with location, unparse, env, headPattern, isVarMatchRule, expandHeadPattern;
Wait, why is this required?  We don't do type checking on `AbstractMatchRule`, and the env provided here would probably be incomplete/wrong.

2021-01-17 23:41 UTC, krame505 commented on grammars/silver/compiler/modification/copper/ParserDcl.sv
> +terminal Parser_kwd 'parser' lexer classes {RESERVED};
Yeah, I think we concluded that this needs to be reserved to avoid an ambiguity with `aspect parser attribute ...`

2021-01-17 23:44 UTC, remexre commented on grammars/silver/compiler/extension/patternmatching/Case.sv
> +nonterminal AbstractMatchRule with location, unparse, env, headPattern, isVarMatchRule, expandHeadPattern;
I did that, we need to look up production types from their names, and they're children of the AMR; it was significantly cleaner to dec the AMR than to rewrite groupMRules to decorate the matches

2021-01-17 23:57 UTC, krame505 commented on grammars/silver/compiler/extension/patternmatching/Case.sv
> +nonterminal AbstractMatchRule with location, unparse, env, headPattern, isVarMatchRule, expandHeadPattern;
Hmm, I guess that's maybe OK.  But I would make sure to be clear that this is the *global* env.

2021-01-18 03:29 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        top::$TypeExpr{aspectTy} ::= $AspectRHS{prodParams}
this has been done now.

2021-01-18 03:29 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +  local defTop::DefLHS = concreteDefLHS(qNameId(name("top",location), location=location), location=location);
same deal, has been done.

2021-01-18 03:30 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +         | _ -> error("This error indicates possible productions for AbstractMatchRule have expanded.")
I have removed it.

2021-01-18 03:30 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/Project.sv
> +imports silver:compiler:analysis:typechecking:core;
Got rid of the unneeded ones.

2021-01-18 06:57 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/ConcreteSyntax.sv
> +    | _ -> error("invalid production type")
Errors have been checked, they're properly reported later so I ignored checking this.

2021-01-18 07:42 UTC, hypnoticOxbow commented
So, I think I've mostly resolved all the outstanding issues, but the mwda analysis is returning errors
that I don't know how to resolve.

Does anybody have any ideas on how to best resolve these issues? afaict both `grammarName` and `frame` attributes are autocopy, so I'm not certain
why they aren't propagating down in these cases.

``` 
Errors for silver:compiler:extension:convenienceaspects
 [/home/ian/Projects/PL-Research/silver/grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv]
AbstractSyntax.sv:63:31: error: Pattern variable '__sv_pv_10057_name' has transitive dependencies with missing remote equations.
	Remote production: silver:compiler:extension:patternmatching:prodAppPattern
	Child: prod
	Missing inherited equations for: silver:compiler:definition:core:grammarName
AbstractSyntax.sv:121:4: error: Equation has transitive dependency on child ml's inherited attribute for silver:compiler:definition:core:frame but this equation appears to be missing.
AbstractSyntax.sv:123:20: error: Access of syn attribute matchRuleList on ml requires missing inherited attributes silver:compiler:definition:core:frame to be supplied
AbstractSyntax.sv:125:55: error: Equation has transitive dependency on child ml's inherited attribute for silver:compiler:definition:core:frame but this equation appears to be missing.
AbstractSyntax.sv:131:39: error: Equation has transitive dependency on child ml's inherited attribute for silver:compiler:definition:core:frame but this equation appears to be missing.
AbstractSyntax.sv:133:37: error: Equation has transitive dependency on child ml's inherited attribute for silver:compiler:definition:core:frame but this equation appears to be missing.
AbstractSyntax.sv:138:2: error: Forward equation exceeds flow type with dependencies on silver:compiler:definition:env:config
AbstractSyntax.sv:138:2: error: Equation has transitive dependency on child ml's inherited attribute for silver:compiler:definition:core:frame but this equation appears to be missing.
```

2021-02-17 02:21 UTC, hypnoticOxbow commented
Ok. MWDA issues have been resolved and I've added checks for wildcard patterns and behavior for `varPatterns` that creates a `let` binding with the appropriate name.

As far as documentation goes, I've added doc comments to the functions I've made, and made a PR for documentation on the website [here](https://github.com/melt-umn/melt-website/pull/20).

2021-02-17 02:23 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +        [wrn(location, "wildcard patterns after this one are dead code.")])
This behavior is resolved now. Patterns after wildcards are now ignored when aspect productions are made, and it outputs a warning if you have patterns after a wildcard.

2021-02-17 02:25 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/patternmatching/Case.sv
> +nonterminal AbstractMatchRule with location, unparse, env, headPattern, isVarMatchRule, expandHeadPattern;
I switched to using the concrete MatchRules and doing lookups with a function, so this change is no longer needed and was reversed.

2021-02-17 16:40 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +  return case l of
oh yea tuple patterns exist now. I'll add these in a sec

2021-02-17 16:42 UTC, krame505 commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +  return case l of
That's not even a tuple pattern, just matching on multiple things at once.  This has been a feature for quite a while.

2021-02-17 17:25 UTC, hypnoticOxbow commented on grammars/silver/compiler/extension/convenienceaspects/AbstractSyntax.sv
> +  return case l of
Ah, I misinterpreted what was added with tuple patterns. The fixes for the comments should be in now.

2021-02-17 17:25 UTC, hypnoticOxbow commented on grammars/silver/compiler/modification/copper/ParserDcl.sv
> +terminal Parser_kwd 'parser' lexer classes {RESERVED};
Added KEYWORD also.

2021-02-17 17:35 UTC, krame505 approved these changes

2021-02-17 20:28 UTC, krame505 commented
@remexre I think this PR needs you to approve it as well before it can be merged since you previously requested changes.

2021-02-17 21:59 UTC, remexre approved these changes

2021-02-17 22:01 UTC, merged