Subprocesses to interact with Silver
melt-umn/silver pull request #446
Opened 2021-01-20 19:49 UTC by RandomActsOfGrammar

This introduces a few functions for working with subprocesses which persist, rather than which run, producing output, and exit.  A Silver grammar may spawn such a process, send it input and read its output (both `stdout` and `stderr`), and wait for it to exit.

Let me know if there are other subprocess interactions that should be added with this now rather than in the future as they are needed.

2021-01-20 20:14 UTC, krame505 requested changes
Looks good, generally.  But can you please also add some tests?

2021-01-20 20:14 UTC, krame505 commented on runtime/java/src/common/ConsCell.java
> +	public static <T> List<T> toList(ConsCell cons) {
Indentation is kinda weird here.

2021-01-20 20:14 UTC, krame505 commented on runtime/java/src/common/IOToken.java
> +
As mentioned, these should probably move to `common.rawlib`

2021-01-20 20:14 UTC, krame505 commented on runtime/java/src/common/ProcessHandle.java
> +package common;
Ditto.

2021-01-20 21:37 UTC, RandomActsOfGrammar commented
If I move this to a library, I need to do one of the following:
1.
2.
3.

2021-01-20 21:38 UTC, krame505 commented
@RandomActsOfGrammar I think part of your comment didn't save.

2021-01-20 21:42 UTC, RandomActsOfGrammar commented
My previous comment was sent before I was ready when I was trying to adjust the size of the box for writing it.  It should make more sense now.

2021-01-20 21:57 UTC, krame505 commented
Hmm.  These functions should definitely take an IO token, and this really doesn't seem like it should be part of `silver:core`.  So I would maybe lean towards making `wrap` public?  Anyone else have thoughts on this?

2021-01-21 05:35 UTC, krame505 approved these changes

2021-01-21 17:46 UTC, RandomActsOfGrammar commented
It turns out---shockingly---that if the output you're reading from a subprocess doesn't end with a newline, reading a line of output  doesn't work.  Therefore I added a couple of functions that will read all available output (one for each of `stdout` and `stderr`) without looking for a particular ending.

2021-01-21 20:05 UTC, merged