Feature/native serialize
melt-umn/silver pull request #541
Opened 2021-07-01 21:30 UTC by 602p

# Changes

Native serialization facility instead of serializing via reflect.

2021-07-02 16:06 UTC, krame505 commented on grammars/silver/reflect/nativeserialize/Util.sv
> +  "java" : return "common.Reflection.nativeDeserialize(typeRep_a0, %x%)"; -- TODO: Hack
Instead of `typerep_a0` you can write `%@0@%` here - `%@i@%` in an ffi string refers to the translation of the ith constraint index dictionary on the function.

2021-07-03 20:24 UTC, 602p commented on grammars/silver/reflect/nativeserialize/Util.sv
> +  "java" : return "common.Reflection.nativeDeserialize(typeRep_a0, %x%)"; -- TODO: Hack
Thanks! I did that.

2021-07-04 15:41 UTC, krame505 commented on grammars/silver/reflect/nativeserialize/Util.sv
> +function writeByteFile
Naming quibble: would prefer to call this `writeBinaryFile`/`readBinaryFile`.  Also these IO functions probably belong in `silver:core` with the rest of the IO functions (and should have monadic versions...)

2021-07-04 15:41 UTC, krame505 commented on grammars/silver/compiler/translation/java/core/NamedSignature.sv
> -		try {
We definitely need to be more consistent with our whitespace... the convention that I've been generally following is using spaces for indenting Silver code and tabs for generated Java code.  But that unfortunately isn't followed everywhere as-is.

2021-07-04 15:41 UTC, krame505 commented on grammars/silver/compiler/translation/java/core/RootSpec.sv
> +	top.genBytesFiles := [
See above comment about whitespace.

2021-07-04 15:41 UTC, krame505 commented on grammars/silver/compiler/translation/java/driver/BuildProcess.sv
> -  return writeFiles(srcPath, r.genFiles, printio);
Would be good to just make `writeSpec` be monadic, at some point... doesn't have to be right now though.

2021-07-04 15:41 UTC, krame505 commented on grammars/test/Main.sv
> +import silver:reflect:nativeserialize;
This belongs in the testsuite, probably in `stdlib`?  Definitely not here.

2021-07-04 15:41 UTC, krame505 commented on runtime/java/src/common/RTTIManager.java
> +import java.security.MessageDigest;
Are these imports used?

2021-07-04 15:41 UTC, krame505 commented on runtime/java/src/common/RTTIManager.java
> +	private static final Map<String, Prodleton<?>> productionsByName = new HashMap<String, Prodleton<?>>(estimateProductionCount, 0.5f); // guesstimates from silver
Move comment to above the actual estimates?

2021-07-04 15:41 UTC, krame505 commented on runtime/java/src/common/Util.java
> +import java.security.MessageDigest;
Are these imports used?

2021-07-06 22:09 UTC, krame505 approved these changes

2021-07-06 22:12 UTC, krame505 requested changes
Wait, it looks like the misplaced test case just got deleted?  This definitely still needs tests.

2021-07-06 23:36 UTC, krame505 commented on test/silver_features/NativeSerialize.sv
> +import silver:reflect:nativeserialize;
I'd say this belongs under `test/stdlib` and not `test/silver_features`.  But otherwise looks good.

2021-07-06 23:50 UTC, 602p commented on test/silver_features/NativeSerialize.sv
> +import silver:reflect:nativeserialize;
I put it in there because that's where the Reflection tests are. I guess maybe the IO tests should be somewhere else, but I wanted to avoid duplicating the example nonterminal.

2021-07-07 16:57 UTC, krame505 approved these changes

2021-07-07 16:59 UTC, merged